server:
  port: 8000

eureka:
  instance:
    # eureka注册中心实例名称
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    # false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    # false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    fetch-registry: false
    service-url:
      defaultZone: ${app.center}
  server:
    enable-self-preservation: false