# 开发环境profile
# 开发环境开启Swagger
swagger:
  enabled: true

# 服务器配置
server:
  port: 8001
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 2000
    accept-count: 2000
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  # 数据源配置
  datasource:
    # hikari连接池配置
    hikari:
      connection-timeout: 30000
  # jpa配置
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  freemarker:
    enabled: true
    charset: UTF-8
    #prefix: classpath:/templates
    suffix: .html
    cache: false