spring:
  profiles:
    active: dev

server:
  port: 8001

# @configurationProperties
dog:
  name: xiaohei
  age: 1

# @Value
pet:
  master: sxy

# logback日志配置
logging:
  file:
    path: D:/Documents/logs/bootApplication
