# 基础配置
spring:
  profiles:
    active: dev
  application:
    name: boot-core
    version: 1.0


# @configurationProperties
dog:
  name: xiaohei
  age: 1

# @Value
pet:
  master: sxy

# logback日志配置
logging:
  file:
    path: D:/Documents/logs/bootApplication
